!SESSION 2020-12-01 16:50:19.767 -----------------------------------------------
eclipse.buildId=4.14.0.I20191210-0610
java.version=1.8.0_261
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_ES
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product

This is a continuation of log file C:\Users\Javier\Desktop\repoJavierCampos\Programacion1\.metadata\.bak_0.log
Created Time: 2020-12-01 16:50:27.547

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:50:27.554
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:50:27.572
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.python.pydev.shared_core 4 4 2020-12-01 16:50:27.578
!MESSAGE Cannot run program "/usr/bin/python3.8" (in directory "C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc"): CreateProcess error=2, El sistema no puede encontrar el archivo especificado
!STACK 0
java.io.IOException: Cannot run program "/usr/bin/python3.8" (in directory "C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc"): CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:64)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:277)
	at org.python.pydev.ast.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:240)
	at org.python.pydev.ast.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:168)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:218)
	at org.python.pydev.ast.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:377)
	at org.python.pydev.ast.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:180)
	at org.python.pydev.ast.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:335)
	at org.python.pydev.ast.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:1)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.getBuiltinMod(AbstractInterpreterManager.java:139)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.getBuiltinCompletions(AbstractInterpreterManager.java:108)
	at org.python.pydev.plugin.nature.PythonNature.getBuiltinCompletions(PythonNature.java:1169)
	at org.python.pydev.ast.codecompletion.revisited.AbstractASTManager.getBuiltinComps(AbstractASTManager.java:1824)
	at org.python.pydev.ast.codecompletion.revisited.AbstractASTManager.getBuiltinCompletions(AbstractASTManager.java:1812)
	at com.python.pydev.analysis.scopeanalysis.AbstractScopeAnalyzerVisitor.<init>(AbstractScopeAnalyzerVisitor.java:152)
	at com.python.pydev.analysis.visitors.OccurrencesVisitor.<init>(OccurrencesVisitor.java:105)
	at com.python.pydev.analysis.OccurrencesAnalyzer.analyzeDocument(OccurrencesAnalyzer.java:54)
	at com.python.pydev.analysis.additionalinfo.builders.AnalysisBuilderRunnable.doAnalysis(AnalysisBuilderRunnable.java:304)
	at com.python.pydev.analysis.additionalinfo.builders.AbstractAnalysisBuilderRunnable.run(AbstractAnalysisBuilderRunnable.java:164)
	at org.python.pydev.core.concurrency.RunnableAsJobsPoolThread$1.run(RunnableAsJobsPoolThread.java:140)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 25 more

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:50:27.586
!MESSAGE Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:50:27.594
!MESSAGE Unable to track file that does not exist: \usr\lib\python3\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.egit.ui 2 0 2020-12-01 16:50:28.089
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Javier'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 4 4 2020-12-01 16:50:57.654
!MESSAGE java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:313)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:279)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:330)
	at org.python.pydev.ast.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:91)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:67)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:325)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SyncSystemModulesManager.java:172)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.updateStructures(SyncSystemModulesManager.java:278)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:311)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more

!ENTRY org.eclipse.core.jobs 4 2 2020-12-01 16:54:28.303
!MESSAGE An internal error occurred during: "List dependencies for: python  (/usr/bin/python3.8)".
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:313)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:279)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:330)
	at org.python.pydev.ui.pythonpathconf.package_manager.PipPackageManager.list(PipPackageManager.java:51)
	at org.python.pydev.ui.pythonpathconf.PackageTab$ListJob.run(PackageTab.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:311)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 10 more

!ENTRY org.python.pydev.shared_core 4 4 2020-12-01 16:54:49.083
!MESSAGE No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
!STACK 0
java.lang.RuntimeException: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInfoFromOutput(AbstractInterpreterManager.java:365)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:70)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:325)
	at org.python.pydev.ui.pythonpathconf.ObtainInterpreterInfoOperation.run(ObtainInterpreterInfoOperation.java:83)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:54:52.617
!MESSAGE - Ok, file is non-null. Getting info on:C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Setting task name:Process finished.
- Success getting the info. Result:<xml>
<name>python1</name>
<version>3.8</version>
<executable>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe</executable>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\DLLs</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\lib</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\lib\site-packages</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>_abc</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_blake2</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_contextvars</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_datetime</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_imp</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_opcode</forced_lib>
<forced_lib>_operator</forced_lib>
<forced_lib>_pickle</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha1</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha3</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_signal</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_stat</forced_lib>
<forced_lib>_statistics</forced_lib>
<forced_lib>_string</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_thread</forced_lib>
<forced_lib>_tracemalloc</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winapi</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>_xxsubinterpreters</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>atexit</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>builtins</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>cv2</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>faulthandler</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>mutagen</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>py</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>re</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>six</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>ssl</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>winreg</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
<string_substitution_var><key>PY</key><value>38</value></string_substitution_var>
</xml>
- Ok, file is non-null. Getting info on:C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Setting task name:Process finished.
Exception detected: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
- Some error happened while getting info on the interpreter:
java.lang.RuntimeException: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInfoFromOutput(AbstractInterpreterManager.java:365)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:70)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:325)
	at org.python.pydev.ui.pythonpathconf.ObtainInterpreterInfoOperation.run(ObtainInterpreterInfoOperation.java:83)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
- Ok, file is non-null. Getting info on:C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Setting task name:Process finished.
- Success getting the info. Result:<xml>
<name>python1</name>
<version>3.8</version>
<executable>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe</executable>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\DLLs</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\lib</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\lib\site-packages</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>_abc</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_blake2</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_contextvars</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_datetime</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_imp</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_opcode</forced_lib>
<forced_lib>_operator</forced_lib>
<forced_lib>_pickle</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha1</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha3</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_signal</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_stat</forced_lib>
<forced_lib>_statistics</forced_lib>
<forced_lib>_string</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_thread</forced_lib>
<forced_lib>_tracemalloc</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winapi</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>_xxsubinterpreters</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>atexit</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>builtins</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>cv2</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>faulthandler</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>mutagen</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>py</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>re</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>six</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>ssl</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>winreg</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
<string_substitution_var><key>PY</key><value>38</value></string_substitution_var>
</xml>

!STACK 0
java.lang.RuntimeException: - Ok, file is non-null. Getting info on:C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Setting task name:Process finished.
- Success getting the info. Result:<xml>
<name>python1</name>
<version>3.8</version>
<executable>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe</executable>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\DLLs</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\lib</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\lib\site-packages</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>_abc</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_blake2</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_contextvars</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_datetime</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_imp</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_opcode</forced_lib>
<forced_lib>_operator</forced_lib>
<forced_lib>_pickle</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha1</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha3</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_signal</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_stat</forced_lib>
<forced_lib>_statistics</forced_lib>
<forced_lib>_string</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_thread</forced_lib>
<forced_lib>_tracemalloc</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winapi</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>_xxsubinterpreters</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>atexit</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>builtins</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>cv2</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>faulthandler</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>mutagen</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>py</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>re</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>six</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>ssl</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>winreg</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
<string_substitution_var><key>PY</key><value>38</value></string_substitution_var>
</xml>
- Ok, file is non-null. Getting info on:C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Setting task name:Process finished.
Exception detected: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
- Some error happened while getting info on the interpreter:
java.lang.RuntimeException: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInfoFromOutput(AbstractInterpreterManager.java:365)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:70)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:325)
	at org.python.pydev.ui.pythonpathconf.ObtainInterpreterInfoOperation.run(ObtainInterpreterInfoOperation.java:83)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
- Ok, file is non-null. Getting info on:C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Setting task name:Process finished.
- Success getting the info. Result:<xml>
<name>python1</name>
<version>3.8</version>
<executable>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\python.exe</executable>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\DLLs</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\lib</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32</lib>
<lib>C:\Users\Javier\AppData\Local\Programs\Python\Python38-32\lib\site-packages</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>_abc</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_blake2</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_contextvars</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_datetime</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_imp</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_opcode</forced_lib>
<forced_lib>_operator</forced_lib>
<forced_lib>_pickle</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha1</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha3</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_signal</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_stat</forced_lib>
<forced_lib>_statistics</forced_lib>
<forced_lib>_string</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_thread</forced_lib>
<forced_lib>_tracemalloc</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winapi</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>_xxsubinterpreters</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>atexit</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>builtins</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>cv2</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>faulthandler</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>mutagen</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>py</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>re</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>six</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>ssl</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>winreg</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
<string_substitution_var><key>PY</key><value>38</value></string_substitution_var>
</xml>

	at org.python.pydev.core.log.Log.logInfo(Log.java:45)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor.getNewInputObject(AbstractInterpreterEditor.java:1043)
	at org.python.copiedfromeclipsesrc.PythonListEditor.addPressed(PythonListEditor.java:142)
	at org.python.copiedfromeclipsesrc.PythonListEditor$1.widgetSelected(PythonListEditor.java:265)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.python.pydev.ui.PyProjectPythonDetails$ProjectInterpreterAndGrammarConfig$2.widgetSelected(PyProjectPythonDetails.java:302)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1098)
	at org.eclipse.swt.widgets.Link.wmNotifyChild(Link.java:713)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5809)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1988)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5375)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4815)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4827)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Link.callWindowProc(Link.java:161)
	at org.eclipse.swt.widgets.Widget.wmLButtonUp(Widget.java:1946)
	at org.eclipse.swt.widgets.Control.WM_LBUTTONUP(Control.java:5188)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4796)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4819)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:153)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:55:23.336
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:55:23.341
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:55:23.347
!MESSAGE Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:55:23.352
!MESSAGE Unable to track file that does not exist: \usr\lib\python3\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.eclipse.core.jobs 4 2 2020-12-01 16:55:33.861
!MESSAGE An internal error occurred during: "List dependencies for: python  (/usr/bin/python3.8)".
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:313)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:279)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:330)
	at org.python.pydev.ui.pythonpathconf.package_manager.PipPackageManager.list(PipPackageManager.java:51)
	at org.python.pydev.ui.pythonpathconf.PackageTab$ListJob.run(PackageTab.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:311)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 10 more

!ENTRY org.python.pydev.shared_core 4 4 2020-12-01 16:55:48.484
!MESSAGE java.lang.RuntimeException: Working dir must be an existing directory (received: \usr\bin)
!STACK 0
java.lang.RuntimeException: java.lang.RuntimeException: Working dir must be an existing directory (received: \usr\bin)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:313)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:279)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:330)
	at org.python.pydev.plugin.nature.PipenvHelper.searchDefaultPipenvLocation(PipenvHelper.java:78)
	at org.python.pydev.ui.pythonpathconf.PipenvDialog.<init>(PipenvDialog.java:54)
	at org.python.pydev.ui.pythonpathconf.InterpreterConfigHelpers.createPipenvInterpreter(InterpreterConfigHelpers.java:343)
	at org.python.pydev.ui.PyProjectPythonDetails$ProjectInterpreterAndGrammarConfig$2.widgetSelected(PyProjectPythonDetails.java:273)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1098)
	at org.eclipse.swt.widgets.Link.wmNotifyChild(Link.java:713)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5809)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1988)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5375)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4815)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4827)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Link.callWindowProc(Link.java:161)
	at org.eclipse.swt.widgets.Widget.wmLButtonUp(Widget.java:1946)
	at org.eclipse.swt.widgets.Control.WM_LBUTTONUP(Control.java:5188)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4796)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4827)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:153)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.RuntimeException: Working dir must be an existing directory (received: \usr\bin)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:304)
	... 58 more

!ENTRY org.eclipse.core.jobs 4 2 2020-12-01 16:56:00.262
!MESSAGE An internal error occurred during: "List dependencies for: python  (/usr/bin/python3.8)".
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:313)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:279)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:330)
	at org.python.pydev.ui.pythonpathconf.package_manager.PipPackageManager.list(PipPackageManager.java:51)
	at org.python.pydev.ui.pythonpathconf.PackageTab$ListJob.run(PackageTab.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:311)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 10 more

!ENTRY org.python.pydev.shared_core 4 4 2020-12-01 16:56:12.272
!MESSAGE No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
!STACK 0
java.lang.RuntimeException: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInfoFromOutput(AbstractInterpreterManager.java:365)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:70)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:325)
	at org.python.pydev.ui.pythonpathconf.ObtainInterpreterInfoOperation.run(ObtainInterpreterInfoOperation.java:83)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 4 4 2020-12-01 16:56:12.297
!MESSAGE Performance warning: LinkedList.get() being called. Consider using another List implementation!
!STACK 0
java.lang.RuntimeException: Performance warning: LinkedList.get() being called. Consider using another List implementation!
	at org.python.pydev.shared_core.log.Log.log(Log.java:38)
	at org.python.pydev.shared_core.structure.LinkedListWarningOnSlowOperations.get(LinkedListWarningOnSlowOperations.java:21)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker.showNothingToConfigureError(AutoConfigMaker.java:451)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker.autoConfigSearch(AutoConfigMaker.java:237)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker.autoConfigSearch(AutoConfigMaker.java:205)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor.getNewInputObject(AbstractInterpreterEditor.java:1002)
	at org.python.copiedfromeclipsesrc.PythonListEditor.addPressed(PythonListEditor.java:142)
	at org.python.copiedfromeclipsesrc.PythonListEditor$1.widgetSelected(PythonListEditor.java:261)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.python.pydev.ui.PyProjectPythonDetails$ProjectInterpreterAndGrammarConfig$2.widgetSelected(PyProjectPythonDetails.java:302)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1098)
	at org.eclipse.swt.widgets.Link.wmNotifyChild(Link.java:713)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5809)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1988)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5375)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4815)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4827)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Link.callWindowProc(Link.java:161)
	at org.eclipse.swt.widgets.Widget.wmLButtonUp(Widget.java:1946)
	at org.eclipse.swt.widgets.Control.WM_LBUTTONUP(Control.java:5188)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4796)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4827)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:153)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:56:19.432
!MESSAGE - Ok, file is non-null. Getting info on:C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Setting task name:Process finished.
Exception detected: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
- Some error happened while getting info on the interpreter:
java.lang.RuntimeException: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInfoFromOutput(AbstractInterpreterManager.java:365)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:70)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:325)
	at org.python.pydev.ui.pythonpathconf.ObtainInterpreterInfoOperation.run(ObtainInterpreterInfoOperation.java:83)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!STACK 0
java.lang.RuntimeException: - Ok, file is non-null. Getting info on:C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe -u C:\Users\Javier\Desktop\eclipse\plugins\org.python.pydev.core_8.0.1.202011071328\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Setting task name:Process finished.
Exception detected: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
- Some error happened while getting info on the interpreter:
java.lang.RuntimeException: No output was in the standard output when
trying to create the interpreter info for: C:\Users\Javier\AppData\Local\Microsoft\WindowsApps\python.exe
The error output contains:>>No se encontr� Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci�n > Administrar alias de ejecuci�n de la aplicaci�n.
<<
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInfoFromOutput(AbstractInterpreterManager.java:365)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:70)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:325)
	at org.python.pydev.ui.pythonpathconf.ObtainInterpreterInfoOperation.run(ObtainInterpreterInfoOperation.java:83)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

	at org.python.pydev.core.log.Log.logInfo(Log.java:45)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor.getNewInputObject(AbstractInterpreterEditor.java:1043)
	at org.python.copiedfromeclipsesrc.PythonListEditor.addPressed(PythonListEditor.java:142)
	at org.python.copiedfromeclipsesrc.PythonListEditor$1.widgetSelected(PythonListEditor.java:261)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.python.pydev.ui.PyProjectPythonDetails$ProjectInterpreterAndGrammarConfig$2.widgetSelected(PyProjectPythonDetails.java:302)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1098)
	at org.eclipse.swt.widgets.Link.wmNotifyChild(Link.java:713)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5809)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1988)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5375)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4815)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4827)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Link.callWindowProc(Link.java:161)
	at org.eclipse.swt.widgets.Widget.wmLButtonUp(Widget.java:1946)
	at org.eclipse.swt.widgets.Control.WM_LBUTTONUP(Control.java:5188)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4796)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4827)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:153)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.eclipse.core.jobs 4 2 2020-12-01 16:56:26.352
!MESSAGE An internal error occurred during: "List dependencies for: python  (/usr/bin/python3.8)".
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:313)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:279)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:330)
	at org.python.pydev.ui.pythonpathconf.package_manager.PipPackageManager.list(PipPackageManager.java:51)
	at org.python.pydev.ui.pythonpathconf.PackageTab$ListJob.run(PackageTab.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:311)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 10 more

!ENTRY org.eclipse.core.jobs 4 2 2020-12-01 16:56:27.864
!MESSAGE An internal error occurred during: "List dependencies for: python  (/usr/bin/python3.8)".
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:313)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:279)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:330)
	at org.python.pydev.ui.pythonpathconf.package_manager.PipPackageManager.list(PipPackageManager.java:51)
	at org.python.pydev.ui.pythonpathconf.PackageTab$ListJob.run(PackageTab.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:311)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 10 more

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:56:52.885
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:56:52.890
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:56:52.895
!MESSAGE Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:56:52.901
!MESSAGE Unable to track file that does not exist: \usr\lib\python3\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:57:14.832
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:57:14.837
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:57:14.843
!MESSAGE Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-01 16:57:14.848
!MESSAGE Unable to track file that does not exist: \usr\lib\python3\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:617)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor$13.run(AbstractInterpreterEditor.java:1184)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
!SESSION 2020-12-02 18:15:09.382 -----------------------------------------------
eclipse.buildId=4.14.0.I20191210-0610
java.version=1.8.0_261
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_ES
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product

!ENTRY org.eclipse.jface 2 0 2020-12-02 18:15:22.746
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2020-12-02 18:15:22.746
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1926f962,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@62794582,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-02 18:15:26.490
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-02 18:15:26.502
!MESSAGE Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3.8\lib-dynload
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-02 18:15:26.511
!MESSAGE Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\local\lib\python3.8\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.python.pydev.shared_core 1 1 2020-12-02 18:15:26.519
!MESSAGE Unable to track file that does not exist: \usr\lib\python3\dist-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: \usr\lib\python3\dist-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.egit.ui 2 0 2020-12-02 18:15:27.263
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Javier'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 4 4 2020-12-02 18:15:56.752
!MESSAGE java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:313)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:279)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:330)
	at org.python.pydev.ast.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:91)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:67)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:325)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SyncSystemModulesManager.java:172)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.updateStructures(SyncSystemModulesManager.java:278)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Cannot run program "/usr/bin/python3.8": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:311)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
